name: fetch data
on:
  workflow_dispatch:
  schedule:
    - cron: '5 8 * * 0'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install all necessary packages
      run: pip install requests pandas altair numpy 
    - name: Run the script
      run: python database.py
    - name: Commit and push if content changed
      run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push